server:
  port: 9527

#在spring boot1.5版本后 Actoator的所以api默认开启了安全验证，这里关闭了安全验证
management:
  security:
    enabled: false

#数据源相关配置：地址、用户名、密码、驱动
spring:
  datasource:
    url: jdbc:mysql://47.99.218.29:3306/campusMarket?characterEncoding=utf-8
    username: root
    password: Gqk_0725
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.js.campus.dao: DEBUG

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml